{
    'name': 'Hospital Management System',
    'version': '1.0',
    'summary': 'Just a simple Hospital Management System',
    'sequence': 0,
    'description': 'A simple hospital management system for Odoo',
    'author': 'Andrew Antwi',
    'website': 'https://www.hospital_management.com',
    'category': 'Healthcare',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'product', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'report/patient_report.xml',
        'views/patient_readonly_views.xml',
        'views/patient_views.xml',
        'views/patient_tag_views.xml',
        'views/appointment_views.xml',
        'views/account_move_views.xml',
        'views/appointment_lines_views.xml',
        'views/doctor_views.xml',
        'views/menu.xml'
    ],
    'installable': True,
    'application': True,
    'auto_install': True,
}
